### ISSUE TITLE
MySQL 创建数据报错

### ISSUE THREAD

**Issue by Chiquitatt** [braisdom/ObjectiveSql#22]
用项目的spring-boot-example，按schema 在mysql 中创建了相应的表，运行Mock.java 报错：

```javascript
Exception in thread "main" java.sql.SQLException: Incorrect integer value: '' for column 'id' at row 1 Query: INSERT INTO `members` (`no`,`name`,`gender`,`mobile`,`other_info`,`id`) VALUES (?,?,?,?,?,?) Parameters: [[M202000001, Joe, 2, 15967733104, null, ], [M202000002, Juan, 2, 18829607597, null, ], [M202000003, Jack, 1, 15111312723, null, ], [M202000004, Albert, 1, 15237313289, null, ], [M202000005, Jonathan, 1, 18755397783, null, ], [M202000006, Justin, 2, 15853597947, null, ], [M202000007, Terry, 2, 15821026238, null, ], [M202000008, Gerald, 2, 15723428182, null, ], [M202000009, Keith, 1, 13259238311, null, ], [M2020000010, Samuel, 2, 18507398025, null, ], [M2020000011, Willie, 2, 13849659158, null, ], [M2020000012, Ralph, 1, 13557191840, null, ], [M2020000013, Lawrence, 2, 18901745643, null, ], [M2020000014, Nicholas, 2, 18929600479, null, ], [M2020000015, Roy, 1, 15371692823, null, ], [M2020000016, Benjamin, 2, 15572807552, null, ], [M2020000017, Bruce, 2, 13101567830, null, ], [M2020000018, Brandon, 1, 13791097127, null, ], [M2020000019, Adam, 1, 13457905664, null, ], [M2020000020, Harry, 1, 15742630260, null, ], [M2020000021, Fred, 1, 15133083189, null, ], [M2020000022, Wayne, 1, 13753053320, null, ], [M2020000023, Billy, 2, 15903166966, null, ], [M2020000024, Steve, 1, 15193293040, null, ], [M2020000025, Louis, 1, 13552643884, null, ], [M2020000026, Jeremy, 2, 13803257731, null, ], [M2020000027, Aaron, 1, 15743962853, null, ], [M2020000028, Randy, 2, 13575172013, null, ], [M2020000029, Howard, 2, 13581268966, null, ], [M2020000030, Eugene, 2, 13231140773, null, ], [M2020000031, Carlos, 1, 18737000766, null, ], [M2020000032, Russell, 2, 18614744707, null, ], [M2020000033, Bobby, 1, 18691984568, null, ], [M2020000034, Victor, 2, 15173804180, null, ], [M2020000035, Martin, 2, 13758099488, null, ], [M2020000036, Ernest, 2, 15632381535, null, ], [M2020000037, Phillip, 1, 13973991517, null, ], [M2020000038, Todd, 1, 18841271283, null, ], [M2020000039, Jesse, 2, 18596665400, null, ], [M2020000040, Craig, 1, 13779891666, null, ], [M2020000041, Alan, 2, 13314220397, null, ], [M2020000042, Shawn, 2, 13266312764, null, ], [M2020000043, Clarence, 2, 15667740533, null, ], [M2020000044, Sean, 2, 13523773472, null, ], [M2020000045, Philip, 2, 18644108580, null, ], [M2020000046, Chris, 1, 15826740755, null, ], [M2020000047, Johnny, 2, 15794869818, null, ], [M2020000048, Earl, 2, 13424396230, null, ], [M2020000049, Jimmy, 2, 13255536759, null, ], [M2020000050, Antonio, 1, 13457680883, null, ], [M2020000051, James, 1, 13205511881, null, ], [M2020000052, John, 1, 18681720326, null, ], [M2020000053, Robert, 1, 18572410795, null, ], [M2020000054, Michael, 2, 13640472002, null, ], [M2020000055, William, 2, 13939748564, null, ], [M2020000056, David, 2, 15921377504, null, ], [M2020000057, Richard, 2, 13306179587, null, ], [M2020000058, Charles, 2, 13307406955, null, ], [M2020000059, Joseph, 1, 13957927921, null, ], [M2020000060, Thomas, 2, 13431734312, null, ], [M2020000061, Christopher, 2, 13412659923, null, ], [M2020000062, Daniel, 2, 15599497931, null, ], [M2020000063, Paul, 2, 15971011783, null, ], [M2020000064, Mark, 1, 15582785959, null, ], [M2020000065, Donald, 1, 18613315910, null, ], [M2020000066, George, 1, 13728589523, null, ], [M2020000067, Kenneth, 1, 13923596548, null, ], [M2020000068, Steven, 1, 15167879768, null, ], [M2020000069, Edward, 1, 15558648515, null, ], [M2020000070, Brian, 2, 13650244514, null, ], [M2020000071, Ronald, 1, 13591980395, null, ], [M2020000072, Anthony, 1, 15304170519, null, ], [M2020000073, Kevin, 1, 15961640264, null, ], [M2020000074, Jason, 1, 13168645287, null, ], [M2020000075, Matthew, 1, 13633257664, null, ], [M2020000076, Gary, 1, 13822977203, null, ], [M2020000077, Timothy, 2, 13209293360, null, ], [M2020000078, Jose, 1, 15795474490, null, ], [M2020000079, Larry, 2, 13395752545, null, ], [M2020000080, Jeffrey, 2, 15629983178, null, ], [M2020000081, Frank, 1, 13580014165, null, ], [M2020000082, Scott, 2, 15743645965, null, ], [M2020000083, Eric, 1, 18888047208, null, ], [M2020000084, Stephen, 1, 15743593592, null, ], [M2020000085, Andrew, 1, 18865653257, null, ], [M2020000086, Raymond, 1, 13556952998, null, ], [M2020000087, Gregory, 1, 13211528625, null, ], [M2020000088, Joshua, 1, 18632189467, null, ], [M2020000089, Jerry, 1, 13108403467, null, ], [M2020000090, Dennis, 2, 15283402397, null, ], [M2020000091, Walter, 2, 13467390417, null, ], [M2020000092, Patrick, 2, 13190899455, null, ], [M2020000093, Peter, 2, 15839626782, null, ], [M2020000094, Harold, 1, 18561015959, null, ], [M2020000095, Douglas, 1, 13476961191, null, ], [M2020000096, Henry, 2, 15565831570, null, ], [M2020000097, Carl, 2, 15332547326, null, ], [M2020000098, Arthur, 2, 18868672568, null, ], [M2020000099, Ryan, 2, 18547487400, null, ], [M20200000100, Roger, 1, 13786120907, null, ]]
	at com.github.braisdom.objsql.jdbc.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:367)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insertBatch(QueryRunner.java:687)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insertBatch(QueryRunner.java:643)
	at com.github.braisdom.objsql.DefaultSQLExecutor.lambda$insert$2(DefaultSQLExecutor.java:58)
	at com.github.braisdom.objsql.Databases.sqlBenchmarking(Databases.java:205)
	at com.github.braisdom.objsql.DefaultSQLExecutor.insert(DefaultSQLExecutor.java:57)
	at com.github.braisdom.objsql.DefaultPersistence.lambda$insert$1(DefaultPersistence.java:117)
	at com.github.braisdom.objsql.Databases.execute(Databases.java:192)
	at com.github.braisdom.objsql.DefaultPersistence.insert(DefaultPersistence.java:100)
	at com.github.braisdom.example.model.Member.create(Member.java:13)
	at com.github.braisdom.example.model.Member.create(Member.java:13)
	at com.github.braisdom.example.Mock.generateMembers(Mock.java:63)
	at com.github.braisdom.example.Mock.generateData(Mock.java:49)
	at com.github.braisdom.example.Mock.main(Mock.java:160)
Caused by: java.sql.BatchUpdateException: Incorrect integer value: '' for column 'id' at row 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
	at com.mysql.cj.util.Util.getInstance(Util.java:167)
	at com.mysql.cj.util.Util.getInstance(Util.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:853)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:796)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insertBatch(QueryRunner.java:685)
	... 12 more
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'id' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:832)
	... 17 more
```

**Comment by catchex** [comment]
ObjectiveSQL 在数据插入时，支持两种过滤主键的方式：
1）在数据模型中增加：`@DomainModel(autoGeneratedPrimaryKey = true)`
2)  在调用 `create` 方法时过滤：`Product.create(products.toArray(new Product[]{}),  false,true);`

两种方式在不同的场景下使用，分别用在模型在每次Insert 时都需要过滤，还有就是在特定的场景下不过滤
