### ISSUE TITLE
IntelliJ 插件报错

### ISSUE THREAD

**Issue by HawkinsBrus** [braisdom/ObjectiveSql#27]
```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  Light PSI class: Table != Light PSI class: Table
  which is 0th element of [Light PSI class: Table] and [Light PSI class: Table]

Recomputation gives com.intellij.util.CachedValueBase$Data@19385316 which is different from both values
Recomputation log:
  Resolving PsiJavaCodeReferenceElement:Relation of class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:92)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:79)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:76)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.github.braisdom.objsql.intellij.ObjSqlPsiAugmentProvider.getAugments(ObjSqlPsiAugmentProvider.java:50)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$getAugments$0(PsiAugmentProvider.java:58)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.augment.PsiAugmentProvider.getAugments(PsiAugmentProvider.java:61)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$2(PsiAugmentProvider.java:110)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:177)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:109)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getInnerClassesMap$10(ClassInnerStuffCache.java:196)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.findInnerClassByName(ClassInnerStuffCache.java:80)
	at com.intellij.psi.impl.source.PsiClassImpl.findInnerClassByName(PsiClassImpl.java:377)
	at com.intellij.psi.impl.PsiClassImplUtil.processCachedMembersByName(PsiClassImplUtil.java:540)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:458)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:435)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:474)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:75)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:221)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:150)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:489)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:185)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
```

**Comment by catchex** [comment]
能提供一些详细信息，或者提供完整的代码，这样也有助我定位问题

**Comment by HawkinsBrus** [comment]
就是你项目里的Demo:
```java
public List<Order> queryOrders(String begin, String end, String[] memberNos)SQLSyntaxException {
    Order.Table order = Order.asTable();
    Member.Table member = Member.asTable();

    Select select = new Select();

    return select.execute(DatabaseType.MySQL, Order.class);
}
```

**Comment by HawkinsBrus** [comment]
有时还会报下面的错，帮忙看一下，老板在让选型ORM 框架，感谢：
```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  38 != 33
  which is length of [ObjSqlLightMethodBuilder#setNo, ObjSqlLightMethodBuilder#getNo, ObjSqlLightMethodBuilder#setName, ObjSqlLightMethodBuilder#getName, ObjSqlLightMethodBuilder#setGender, ObjSqlLightMethodBuilder#getGender, ObjSqlLightMethodBuilder#setMobile, ObjSqlLightMethodBuilder#getMobile, ObjSqlLightMethodBuilder#setId, ObjSqlLightMethodBuilder#getId, ObjSqlLightMethodBuilder#queryByPrimaryKey, ObjSqlLightMethodBuilder#createQuery, ObjSqlLightMethodBuilder#count, ObjSqlLightMethodBuilder#countAll, ObjSqlLightMethodBuilder#query, ObjSqlLightMethodBuilder#query, ObjSqlLightMethodBuilder#queryBySql, ObjSqlLightMethodBuilder#queryFirst, ObjSqlLightMethodBuilder#queryFirst, ObjSqlLightMethodBuilder#queryAll, ObjSqlLightMethodBuilder#createPersistence, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#update, ObjSqlLightMethodBuilder#update, ObjSqlLightMethodBuilder#destroy, ObjSqlLightMethodBuilder#destroy, ObjSqlLightMethodBuilder#save, ObjSqlLightMethodBuilder#save, ObjSqlLightMethodBuilder#validate, ObjSqlLightMethodBuilder#execute, ObjSqlLightMethodBuilder#newInstanceFrom, ObjSqlLightMethodBuilder#newInstanceFrom, ObjSqlLightMethodBuilder#getRawAttributes, ObjSqlLightMethodBuilder#getRawAttribute, ObjSqlLightMethodBuilder#asTable] and [ObjSqlLightMethodBuilder#setNo, ObjSqlLightMethodBuilder#getNo, ObjSqlLightMethodBuilder#setName, ObjSqlLightMethodBuilder#setId, ObjSqlLightMethodBuilder#getId, ObjSqlLightMethodBuilder#queryByPrimaryKey, ObjSqlLightMethodBuilder#createQuery, ObjSqlLightMethodBuilder#count, ObjSqlLightMethodBuilder#countAll, ObjSqlLightMethodBuilder#query, ObjSqlLightMethodBuilder#query, ObjSqlLightMethodBuilder#queryBySql, ObjSqlLightMethodBuilder#queryFirst, ObjSqlLightMethodBuilder#queryFirst, ObjSqlLightMethodBuilder#queryAll, ObjSqlLightMethodBuilder#createPersistence, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#update, ObjSqlLightMethodBuilder#update, ObjSqlLightMethodBuilder#destroy, ObjSqlLightMethodBuilder#destroy, ObjSqlLightMethodBuilder#save, ObjSqlLightMethodBuilder#save, ObjSqlLightMethodBuilder#validate, ObjSqlLightMethodBuilder#execute, ObjSqlLightMethodBuilder#newInstanceFrom, ObjSqlLightMethodBuilder#newInstanceFrom, ObjSqlLightMethodBuilder#getRawAttributes, ObjSqlLightMethodBuilder#getRawAttribute, ObjSqlLightMethodBuilder#asTable]

Recomputation gives com.intellij.util.CachedValueBase$Data@5177ed00 which is different from both values
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:91)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:78)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:154)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:43)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:278)
	at com.intellij.psi.impl.PsiClassImplUtil.lambda$createMembersMap$4(PsiClassImplUtil.java:343)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:181)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.get(PsiClassImplUtil.java:326)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.access$000(PsiClassImplUtil.java:318)
	at com.intellij.psi.impl.PsiClassImplUtil.processCachedMembersByName(PsiClassImplUtil.java:531)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:412)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:389)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:476)
	at com.intellij.psi.scope.util.PsiScopesUtil.processQualifierResult(PsiScopesUtil.java:499)
	at com.intellij.psi.scope.util.PsiScopesUtil.setupAndRunProcessor(PsiScopesUtil.java:344)
```

**Comment by catchex** [comment]
@HawkinsBrus 这两个问题本质上是ObjSqlLightMethodBuilder 中缺省的equals 方法问题（使用的Java 缺省的equals），导致CachedValueBase 中两次处理时，同样的方法一不致，JDK 缺省是这样的。
```java
public boolean equals(Object obj) {
    return (this == obj);
}
```
