### ISSUE TITLE
it returns different results when invoked multiple times or on different threads:   38 != 30

### ISSUE THREAD

**Issue by HawkinsBrus** [braisdom/ObjectiveSql#31]
我在编码的过程中，IntelliJ 报了这个错，随机的，完整的堆栈如下，望尽快修复：
```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  38 != 30
  which is length of [ObjSqlLightMethodBuilder#setNo, ObjSqlLightMethodBuilder#getNo, ObjSqlLightMethodBuilder#setName, ObjSqlLightMethodBuilder#getName, ObjSqlLightMethodBuilder#setGender, ObjSqlLightMethodBuilder#getGender, ObjSqlLightMethodBuilder#setMobile, ObjSqlLightMethodBuilder#getMobile, ObjSqlLightMethodBuilder#setId, ObjSqlLightMethodBuilder#getId, ObjSqlLightMethodBuilder#queryByPrimaryKey, ObjSqlLightMethodBuilder#createQuery, ObjSqlLightMethodBuilder#count, ObjSqlLightMethodBuilder#countAll, ObjSqlLightMethodBuilder#query, ObjSqlLightMethodBuilder#query, ObjSqlLightMethodBuilder#queryBySql, ObjSqlLightMethodBuilder#queryFirst, ObjSqlLightMethodBuilder#queryFirst, ObjSqlLightMethodBuilder#queryAll, ObjSqlLightMethodBuilder#createPersistence, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#update, ObjSqlLightMethodBuilder#update, ObjSqlLightMethodBuilder#destroy, ObjSqlLightMethodBuilder#destroy, ObjSqlLightMethodBuilder#save, ObjSqlLightMethodBuilder#save, ObjSqlLightMethodBuilder#validate, ObjSqlLightMethodBuilder#execute, ObjSqlLightMethodBuilder#newInstanceFrom, ObjSqlLightMethodBuilder#newInstanceFrom, ObjSqlLightMethodBuilder#getRawAttributes, ObjSqlLightMethodBuilder#getRawAttribute, ObjSqlLightMethodBuilder#asTable] and [ObjSqlLightMethodBuilder#setId, ObjSqlLightMethodBuilder#getId, ObjSqlLightMethodBuilder#queryByPrimaryKey, ObjSqlLightMethodBuilder#createQuery, ObjSqlLightMethodBuilder#count, ObjSqlLightMethodBuilder#countAll, ObjSqlLightMethodBuilder#query, ObjSqlLightMethodBuilder#query, ObjSqlLightMethodBuilder#queryBySql, ObjSqlLightMethodBuilder#queryFirst, ObjSqlLightMethodBuilder#queryFirst, ObjSqlLightMethodBuilder#queryAll, ObjSqlLightMethodBuilder#createPersistence, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#create, ObjSqlLightMethodBuilder#update, ObjSqlLightMethodBuilder#update, ObjSqlLightMethodBuilder#destroy, ObjSqlLightMethodBuilder#destroy, ObjSqlLightMethodBuilder#save, ObjSqlLightMethodBuilder#save, ObjSqlLightMethodBuilder#validate, ObjSqlLightMethodBuilder#execute, ObjSqlLightMethodBuilder#newInstanceFrom, ObjSqlLightMethodBuilder#newInstanceFrom, ObjSqlLightMethodBuilder#getRawAttributes, ObjSqlLightMethodBuilder#getRawAttribute, ObjSqlLightMethodBuilder#asTable]

Recomputation gives com.intellij.util.CachedValueBase$Data@26fbcccc which is equivalent to 'fresh'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:91)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:78)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:154)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:43)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:278)
	at com.intellij.psi.impl.PsiClassImplUtil.lambda$createMembersMap$4(PsiClassImplUtil.java:343)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:181)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.get(PsiClassImplUtil.java:326)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.access$000(PsiClassImplUtil.java:318)
	at com.intellij.psi.impl.PsiClassImplUtil.processCachedMembersByName(PsiClassImplUtil.java:531)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:412)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:389)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:476)
	at com.intellij.psi.scope.util.PsiScopesUtil.processQualifierResult(PsiScopesUtil.java:499)
	at com.intellij.psi.scope.util.PsiScopesUtil.setupAndRunProcessor(PsiScopesUtil.java:344)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToMethod(PsiReferenceExpressionImpl.java:323)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:302)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$100(PsiReferenceExpressionImpl.java:50)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:205)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:181)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:182)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:225)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:202)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:182)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:786)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:778)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:365)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.advancedResolve(PsiReferenceExpressionImpl.java:527)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:826)
	at com.android.tools.idea.AndroidPsiUtils.getResourceReferenceType(AndroidPsiUtils.java:302)
	at com.android.tools.idea.folding.ResourceFoldingBuilder.findJavaExpressionReference(ResourceFoldingBuilder.java:164)
	at com.android.tools.idea.folding.ResourceFoldingBuilder.access$000(ResourceFoldingBuilder.java:47)
	at com.android.tools.idea.folding.ResourceFoldingBuilder$1.visitReferenceExpression(ResourceFoldingBuilder.java:94)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:805)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:340)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:482)
	at com.android.tools.idea.folding.ResourceFoldingBuilder.buildFoldRegions(ResourceFoldingBuilder.java:91)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:92)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:37)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:92)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:75)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:243)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:223)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:81)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.lambda$updateFoldRegions$0(FoldingUpdate.java:70)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:67)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:229)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:402)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by catchex** [comment]
与 #27  同一个问题导致，主要是因为：PsiAugmentProvider 中的CachedValuesManager 数据必须一致，而之前是根据条件对数据进行了过滤，所以导致了这个问题。
