### ISSUE TITLE
在PostgreSQL 中插入Timestamp 类型报错

### ISSUE THREAD

**Issue by oliviaour** [braisdom/ObjectiveSql#37]
ObjectiveSQL 1.3.7
插入代码：
```java
Order order = new Order()
                .setNo("202000001")
                .setMemberId(3)
                .setAmount(3.5d)
                .setQuantity(100.3d)
                .setSalesAt(Timestamp.valueOf("2020-05-01 09:30:00"));
        order.save(false, true);
```
异常信息
```
java.sql.SQLException: ERROR: column "sales_at" is of type timestamp without time zone but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：92 Query: INSERT INTO "orders" ("no","member_id","amount","quantity","sales_at") VALUES (?,?,?,?,?) Parameters: [202000001, 3, 3.5, 100.3, 2020-05-01 09:30:00.0]

	at com.github.braisdom.objsql.jdbc.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:369)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insert(QueryRunner.java:605)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insert(QueryRunner.java:560)
	at com.github.braisdom.objsql.DefaultSQLExecutor.lambda$insert$1(DefaultSQLExecutor.java:50)
	at com.github.braisdom.objsql.Databases.sqlBenchmarking(Databases.java:206)
	at com.github.braisdom.objsql.DefaultSQLExecutor.insert(DefaultSQLExecutor.java:49)
	at com.github.braisdom.objsql.DefaultPersistence.lambda$insert$0(DefaultPersistence.java:82)
	at com.github.braisdom.objsql.Databases.execute(Databases.java:193)
	at com.github.braisdom.objsql.DefaultPersistence.insert(DefaultPersistence.java:70)
	at com.github.braisdom.objsql.DefaultPersistence.save(DefaultPersistence.java:52)
	at com.github.braisdom.objsql.example.domains.Order.save(Order.java:15)
	at com.github.braisdom.objsql.example.PersistenceExample.createOrder(PersistenceExample.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by catchex** [comment]
收到，这应该是我忽略了，我会抓紧时候修复，不同数据库的类型适配可能不完善，会增加到单元测试中。感谢支持

**Comment by oliviaour** [comment]
https://github.com/braisdom/ObjectiveSql/commit/4ae5730ad3e087c2f682844bba4136fb83ae39f5

里面对其它数据库的处理可能还会存在问题。本问题已经修复
