### ISSUE TITLE
PostgreSQL 插件错误（急！！！！）

### ISSUE THREAD

**Issue by HawkinsBrus** [braisdom/ObjectiveSql#38]
大佬，我们用PostgreSQL 数据，插入数据报错，帮忙看一下，急！！！！

```
java.sql.SQLException: Batch entry 0 INSERT INTO "members" ("no","name","gender","mobile","extended_attributes","registered_at","updated_at") VALUES ('200001','Alice',0,'15011112222','null',NULL,NULL)
RETURNING * was aborted: ERROR: column "registered_at" is of type timestamp without time zone but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：129  Call getNextException to see other errors in the batch. Query: INSERT INTO "members" ("no","name","gender","mobile","extended_attributes","registered_at","updated_at") VALUES (?,?,?,?,?,?,?) Parameters: [[200001, Alice, 0, 15011112222, null, null, null], [200003, Mary, 0, 15011112222, null, null, null], [200004, Denise, 0, 15011112222, null, null, null]]

	at com.github.braisdom.objsql.jdbc.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:369)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insertBatch(QueryRunner.java:687)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insertBatch(QueryRunner.java:643)
	at com.github.braisdom.objsql.DefaultSQLExecutor.lambda$insert$2(DefaultSQLExecutor.java:58)
	at com.github.braisdom.objsql.Databases.sqlBenchmarking(Databases.java:206)
	at com.github.braisdom.objsql.DefaultSQLExecutor.insert(DefaultSQLExecutor.java:57)
	at com.github.braisdom.objsql.DefaultPersistence.lambda$insert$1(DefaultPersistence.java:123)
	at com.github.braisdom.objsql.Databases.execute(Databases.java:193)
	at com.github.braisdom.objsql.DefaultPersistence.insert(DefaultPersistence.java:105)
	at com.github.braisdom.objsql.example.domains.Member.create(Member.java:15)
	at com.github.braisdom.objsql.example.PersistenceExample.createMemberWithArray(PersistenceExample.java:121)
	at com.github.braisdom.objsql.example.PersistenceExample.executeDeleteDenise(PersistenceExample.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "members" ("no","name","gender","mobile","extended_attributes","registered_at","updated_at") VALUES ('200001','Alice',0,'15011112222','null',NULL,NULL)
RETURNING * was aborted: ERROR: column "registered_at" is of type timestamp without time zone but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：129  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:199)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:855)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insertBatch(QueryRunner.java:685)
	... 33 more

```

**Comment by catchex** [comment]
你可以一下commit: https://github.com/braisdom/ObjectiveSql/commit/4ae5730ad3e087c2f682844bba4136fb83ae39f5

这个问题我跑单元测试时也遇到，应该是之前重构FieldValue 时候的错误，如果已经修复，请关闭该issue，如果还有其它问题欢迎交流。

**Comment by HawkinsBrus** [comment]
更新了代码，已经OK，感谢
