### ISSUE TITLE
Failed to write Order.memberId, because setter method require Integer

### ISSUE THREAD

**Issue by augustinexx** [braisdom/ObjectiveSql#39]
运行下面代码：
```java
Relationship[] memberRelation = new Relationship[]{Order.BELONGS_TO_MEMBER};
Order order = Order.queryByPrimaryKey(1L, memberRelation);
```
报错:
```
java.sql.SQLException: Failed to write Order.memberId, because setter method require Integer, but give a Long(1)

	at com.github.braisdom.objsql.Databases.sqlBenchmarking(Databases.java:220)
	at com.github.braisdom.objsql.DefaultSQLExecutor.query(DefaultSQLExecutor.java:41)
	at com.github.braisdom.objsql.DefaultQuery.lambda$execute$0(DefaultQuery.java:49)
	at com.github.braisdom.objsql.Databases.execute(Databases.java:193)
	at com.github.braisdom.objsql.DefaultQuery.execute(DefaultQuery.java:44)
	at com.github.braisdom.objsql.DefaultQuery.queryFirst(DefaultQuery.java:61)
	at com.github.braisdom.objsql.example.domains.Order.queryByPrimaryKey(Order.java:15)
	at com.github.braisdom.objsql.example.RelationExample.queryBelongsTo(RelationExample.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: com.github.braisdom.objsql.reflection.ReflectionException: Failed to write Order.memberId, because setter method require Integer, but give a Long(1)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:142)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:122)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:118)
	at com.github.braisdom.objsql.BeanModelDescriptor.setFieldValue(BeanModelDescriptor.java:279)
	at com.github.braisdom.objsql.DomainModelListHandler.createBean(DefaultSQLExecutor.java:120)
	at com.github.braisdom.objsql.DomainModelListHandler.handle(DefaultSQLExecutor.java:88)
	at com.github.braisdom.objsql.DomainModelListHandler.handle(DefaultSQLExecutor.java:68)
	at com.github.braisdom.objsql.jdbc.QueryRunner.query(QueryRunner.java:343)
	at com.github.braisdom.objsql.jdbc.QueryRunner.query(QueryRunner.java:207)
	at com.github.braisdom.objsql.DefaultSQLExecutor.lambda$query$0(DefaultSQLExecutor.java:42)
	at com.github.braisdom.objsql.Databases.sqlBenchmarking(Databases.java:206)
	... 30 more
```

**Comment by catchex** [comment]
异常日志中已经明确说明：“ because setter method require Integer, but give a Long(1)”
在DomainModel 中定义的Order.memberId，但给定的值为Long ，这种情况一般会出现在数据库类型转换。

**Comment by catchex** [comment]
我已经采用了BeanUtils 中的方法转换，不会再出现这样的问题：
```java
ConvertUtilsBean convertUtilsBean = BeanUtilsBean.getInstance().getConvertUtils();
Object convertedValue = convertUtilsBean.convert(value, propertyDescriptor.getPropertyType());
```

详细请参考：https://github.com/braisdom/ObjectiveSql/blob/master/core/src/main/java/com/github/braisdom/objsql/reflection/PropertyUtils.java#L130
