### ISSUE TITLE
java.sql.SQLException: Failed to write Member.id, because setter method require Long, but give a BigDecimal(1)

### ISSUE THREAD

**Issue by activepirate** [braisdom/ObjectiveSql#40]
使用sqlserver保持数据的时候会报错，怎么解决啊
数据模型:
```
@DomainModel
public class Member {
    @Size(min = 5, max = 20)
    private String no;

    @Queryable
    private String name;

    @Queryable
    private Integer gender;
    private String mobile;
}
```
数据保存:
```
Member member = Member.create(newMember, true, true);
```
报错信息:
```
java.sql.SQLException: Failed to write Member.id, because setter method require Long, but give a BigDecimal(1)

	at com.github.braisdom.objsql.Databases.sqlBenchmarking(Databases.java:220)
	at com.github.braisdom.objsql.DefaultSQLExecutor.insert(DefaultSQLExecutor.java:49)
	at com.github.braisdom.objsql.DefaultPersistence.lambda$insert$0(DefaultPersistence.java:82)
	at com.github.braisdom.objsql.Databases.execute(Databases.java:193)
	at com.github.braisdom.objsql.DefaultPersistence.insert(DefaultPersistence.java:70)
	at com.github.braisdom.objsql.example.domains.Member.create(Member.java:15)
	at com.github.braisdom.objsql.example.PersistenceExample.createSimpleMemberSkipValidation(PersistenceExample.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.github.braisdom.objsql.reflection.ReflectionException: Failed to write Member.id, because setter method require Long, but give a BigDecimal(1)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:142)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:122)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:118)
	at com.github.braisdom.objsql.BeanModelDescriptor.setFieldValue(BeanModelDescriptor.java:279)
	at com.github.braisdom.objsql.BeanModelDescriptor.setGeneratedKey(BeanModelDescriptor.java:135)
	at com.github.braisdom.objsql.DomainModelHandler.handle(DefaultSQLExecutor.java:162)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insert(QueryRunner.java:603)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insert(QueryRunner.java:560)
	at com.github.braisdom.objsql.DefaultSQLExecutor.lambda$insert$1(DefaultSQLExecutor.java:50)
	at com.github.braisdom.objsql.Databases.sqlBenchmarking(Databases.java:206)
	... 29 more
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.github.braisdom.objsql.reflection.PropertyUtils.lambda$write$3(PropertyUtils.java:132)
	at com.github.braisdom.objsql.reflection.PropertyUtils.withAccessibleObject(PropertyUtils.java:325)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:132)
	... 38 more
```

**Comment by catchex** [comment]
与 #39 同样的问题，请参考我的回复，感谢支持
