### ISSUE TITLE
com.github.braisdom.objsql.reflection.ReflectionException: Failed to write Member.id, because setter method require Integer, but give a Long(10)

### ISSUE THREAD

**Issue by LuckZZ** [braisdom/ObjectiveSql#41]
使用mysql保存数据报错
数据模型:
```
@DomainModel(primaryClass = Integer.class)
public class Member {
    @Size(min = 5, max = 20)
    private String no;

    @Queryable
    private String name;

    @Queryable
    private Integer gender;
    private String mobile;
}
```
数据保存:
```
Member member = Member.create(newMember, true, true);
```
报错信息:
```
com.github.braisdom.objsql.reflection.ReflectionException: Failed to write Member.id, because setter method require Integer, but give a Long(10)

	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:142)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:122)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:118)
	at com.github.braisdom.objsql.reflection.PropertyUtils.populate(PropertyUtils.java:191)
	at com.github.braisdom.objsql.example.domains.Member.newInstanceFrom(Member.java:15)
	at com.github.braisdom.objsql.example.PersistenceExample.createSimpleMemberCopyFromMap(PersistenceExample.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.github.braisdom.objsql.reflection.PropertyUtils.lambda$write$3(PropertyUtils.java:132)
	at com.github.braisdom.objsql.reflection.PropertyUtils.withAccessibleObject(PropertyUtils.java:325)
	at com.github.braisdom.objsql.reflection.PropertyUtils.write(PropertyUtils.java:132)
	... 28 more
```

**Comment by catchex** [comment]
与 #39 #40  重复，请参考，我先关闭，其它两个问题修复后，请关闭，感谢支持
