### ISSUE TITLE
mysql表没有主键自增会报错怎么处理

### ISSUE THREAD

**Issue by LuckZZ** [braisdom/ObjectiveSql#54]
mysql表没有主键自增会报错
DDL：
```
CREATE TABLE `objective_sql`.`members`(
   `id` INT UNSIGNED,
   `no` VARCHAR(100),
   `name` VARCHAR(100),
   `gender` INT(2),
   `mobile` VARCHAR(11),
   `extended_attributes` VARCHAR(512),
   `registered_at` DATETIME,
   `updated_at` DATETIME,
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
新增代码：
```
Member newMember = new Member();
newMember.setId(2L)
        .setNo("100000")
        .setName("Pamela")
        .setGender(1)
        .setRegisteredAtWithJoda(DateTime.now())
        .setUpdatedAt(Timestamp.valueOf("2020-10-05 00:00:00"))
        .setMobile("15011112222");

Member member = Member.create(newMember, true, true);
```
报错信息：
```
java.sql.SQLException: Field 'id' doesn't have a default value Query: INSERT INTO `members` (`no`,`name`,`gender`,`mobile`,`extended_attributes`,`registered_at`,`updated_at`) VALUES (?,?,?,?,?,?,?) Parameters: [100000, Pamela, 1, 15011112222, null, 2020-11-26 17:35:54.318, 2020-10-05 00:00:00.0]

	at com.github.braisdom.objsql.jdbc.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:369)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insert(QueryRunner.java:605)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insert(QueryRunner.java:560)
	at com.github.braisdom.objsql.DefaultSQLExecutor.lambda$insert$1(DefaultSQLExecutor.java:50)
	at com.github.braisdom.objsql.Databases.sqlBenchmarking(Databases.java:229)
	at com.github.braisdom.objsql.DefaultSQLExecutor.insert(DefaultSQLExecutor.java:49)
	at com.github.braisdom.objsql.DefaultPersistence.lambda$insert$0(DefaultPersistence.java:82)
	at com.github.braisdom.objsql.Databases.execute(Databases.java:216)
	at com.github.braisdom.objsql.DefaultPersistence.insert(DefaultPersistence.java:70)
	at com.github.braisdom.objsql.example.domains.Member.create(Member.java:15)
	at com.github.braisdom.objsql.example.PersistenceExample.createSimpleMemberSkipValidation(PersistenceExample.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.sql.SQLException: Field 'id' doesn't have a default value
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insert(QueryRunner.java:601)
	... 32 more
```

**Comment by catchex** [comment]
版本信息提供一下。

**Comment by catchex** [comment]
```java
Member member = Member.create(newMember, true, true);
```
第一个 "true" 是跳过validation， 第二个 "true" 是跳过 skipPrimaryKeyOnInserting
你按上述代码就可以使用你自己设置的主键值了

**Comment by catchex** [comment]
这应该是一个Bug 解决后说明原因
