### ISSUE TITLE
HSQLDB 支持有问题

### ISSUE THREAD

**Issue by augustinexx** [braisdom/ObjectiveSql#56]
SQL:
```sql
INSERT INTO "user" ("id","name","age") VALUES (?,?,?)
```

异常信息
```
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: user
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:317)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at com.github.braisdom.objsql.jdbc.QueryRunner.insert(QueryRunner.java:599)
	... 24 more
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: user
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.SchemaManager.getTable(Unknown Source)
	at org.hsqldb.ParserDQL.readTableName(Unknown Source)
	at org.hsqldb.ParserDQL.readRangeVariableForDataChange(Unknown Source)
	at org.hsqldb.ParserDML.compileInsertStatement(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 29 more
```

**Comment by catchex** [comment]
应该是quote 有问题，之前没有兼容

**Comment by AlbertaAllen** [comment]
我的项目也遇到这个问题了，大佬啥时候解决呀。
