### ISSUE TITLE
所有API 均报错

### ISSUE THREAD

**Issue by catchex** [braisdom/ObjectiveSql#87]
![image](https://user-images.githubusercontent.com/875473/102354002-e6128980-3fe4-11eb-8733-a2dc22fe71b4.png)

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'aClass' of com/intellij/psi/impl/PsiElementFactoryImpl.createType must not be null
 at com.intellij.psi.impl.PsiElementFactoryImpl.$$$reportNull$$$0(PsiElementFactoryImpl.java)
 at com.intellij.psi.impl.PsiElementFactoryImpl.createType(PsiElementFactoryImpl.java)
 at com.github.braisdom.objsql.intellij.ObjSqlPsiAugmentProvider.createParameterType(ObjSqlPsiAugmentProvider.java:170)
 at com.github.braisdom.objsql.intellij.ObjSqlPsiAugmentProvider.createParameterType(ObjSqlPsiAugmentProvider.java:158)
 at com.github.braisdom.objsql.intellij.QueryMethodBuilder.buildPagedQuery(QueryMethodBuilder.java:80)
 at com.github.braisdom.objsql.intellij.QueryMethodBuilder.buildMethod(QueryMethodBuilder.java:18)
 at com.github.braisdom.objsql.intellij.ObjSqlPsiAugmentProvider$ObjSqlCachedValueProvider.lambda$compute$0(ObjSqlPsiAugmentProvider.java:102)
 at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
 at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
 at com.github.braisdom.objsql.intellij.ObjSqlPsiAugmentProvider$ObjSqlCachedValueProvider.compute(ObjSqlPsiAugmentProvider.java:96)
 at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
 at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
 at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
 at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
 at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
 at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
 at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
 at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
 at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:78
```

**Comment by catchex** [comment]
该问题为代提，是由于IntelliJ 版本使用1.3.2 而objective-sql 的Runtime 版本使用1.3.5 版本 导致版本过低不支持的问题。
